const main = async () => {};

main()
  .then()
  .catch((error) => console.error(error));
